config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :users, :only => [:index, :show]
  resources :links
  get 'feature_pages/manage'

  get 'feature_pages/view'

  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

  root 'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Selector::API => '/api/'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #devise :database_authenticatable, :registerable, :confirmable,
  #       :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :trackable, :omniauthable

  def self.find_for_google_oauth2(auth)
    user = User.where(email: auth.info.email).first

    unless user
      user = User.create(name: auth.info.name,
                         provider: auth.provider,
                         uid: auth.uid,
                         email: auth.info.email,
                         token: auth.credentials.token,
                         password: Devise.friendly_token[0, 20],
                         #confirmed_at: Time.zone.now
      )
    end
    user
  end

  has_many :links, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
    def signed_in_user
      redirect_to root_path, notice: "Please signup or signin." unless signed_in?
    end

end

app/controllers/feature_pages_controller.rb
class FeaturePagesController < ApplicationController
  before_action :signed_in_user
  def manage
    @links = Link.all
  end

  def view
    @mals_url = "#{root_url}"
    @mals_js_path = "mals.js?malskey=#{User.find(current_user.id).hashed_email}"
    @mals_div_id = "mals_replace_target"
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :signed_in_user
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    #@links = Link.all
    @user = User.find(current_user.id)
    @links = @user.links
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    #@link = Link.new(link_params)
    @user = User.find(current_user.id)
    @link = @user.links.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:sort, :description, :link, :enabled)
    end

    def correct_user
      @user = User.find(Link.find(params[:id]).user_id)
      unless current_user?(@user)
        logger.warn("Invalid access on Links. #{current_user.email} to #{request.method} #{request.url}")
        redirect_to root_path, notice: "Please signin with correct user."
      end
    end

    def current_user?(user)
      user == current_user
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.find_for_google_oauth2(request.env["omniauth.auth"])
    # check whether a user exists.
    if @user.persisted?
      #ogger.debug("========== DEBUG ==========")
      #logger.debug("persisted: #{@user.inspect}")
      # Original update save hashed_email for javascript key
      @user.update(hashed_email: Digest::SHA2.hexdigest(@user.email))
      #logger.debug("========== DEBUG ==========")
      #logger.debug("persisted: #{@user.inspect}")
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  def index
    #@users = User.all
    @users = [User.find(current_user.id)]
  end

  def show
    @user = User.find(params[:id])
    logger.info(@user)
    @links = @user.links.build(user_id:@user.id)
  end

  private
    def correct_user
      #@current_user ||= User.find_by(params[:id])
      @user = User.find(params[:id])
      unless current_user?(@user)
        logger.warn("Invalid access on Users. #{current_user.email} to #{request.method} #{request.url}")
        redirect_to root_path, notice: "Please signin with correct user."
      end
    end

    def current_user?(user)
      user == current_user
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feature_pages_helper.rb
module FeaturePagesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feature_pages/manage.html.slim
h1
  | Ad Links Manager
p
  | Find me in app/views/feature_pages/manage.html.erb

h2
  | リンクを編集してください。

- @links.each do |link|
  p
  b Description:
  = link.description
  p
  b Link:
  = link.link

app/views/feature_pages/view.html.slim
h1
  | LinkRack View
p
  | Find me in app/views/feature_pages/view.html.erb

h3
  | 広告を表示したい箇所に以下のコードを挿入してください。
pre
  | &lt;div id="#{@mals_div_id}"&gt;&lt;/div&gt;
  br
  | &lt;script src="#{@mals_url}#{@mals_js_path}"&gt;&lt;/script&gt;
h2
  | 表示サンプル
p
  | 現状の設定では以下の広告が表示されます。(ページ更新で登録中の広告からランダム表示)
  div class="panel panel-default"
    div class="panel-heading"
      h4 表示例
    div class="panel-body"
      div id="#{@mals_div_id}"
        | This message will be replaced.
script src="/#{@mals_js_path}"
//= javascript_include_tag 'feature_pages', 'data-turbolinks-track': 'reload'

app/views/layouts/_footer.html.slim
div class="row"
hr
  div class="col-md-1"
    h3
      | Menu
  div class="col-md-2"
    ul
      li = link_to 'home', '/'
      li = link_to 'about', '/static_pages/about'
      li = link_to 'help', '/static_pages/help'
  div class="col-md-1"
    h3
      | Feature
  div class="col-md-2"
    ul
      /li = link_to 'manage', '/feature_pages/manage'
      li = link_to 'view', '/feature_pages/view'
      li = link_to 'links', '/links'
      li = link_to 'user', '/users'

app/views/layouts/_header.html.slim
div class="navbar navbar-default navbar-fixed-top"
  /role="navigation"
  div class="container"
    div class="navbar-inner"
      div class="navbar-header"
        div class="navbar-brand"
          = link_to "LinkRack", root_path, id: "logo"
      div id="navbar" class="nav-collapse" data-toggle="collapse" data-target=".nav-collapse"
        ul class="nav navbar-nav navbar-right"
          - if user_signed_in?
            li = link_to current_user.email, '/users'
            li = link_to 'Signout', destroy_user_session_path, method: :delete
          - unless user_signed_in?
            li = link_to "Not Logged In", '#'
            li = link_to 'Signin with Google', user_google_oauth2_omniauth_authorize_path

  / button class="btn btn-danger"
  /   = link_to 'Unsubscribe', '/users', method: :delete, data: { confirm: "Really want to UNSUBSCRIBE?\nYour links will be removed!!" }  if user_signed_in?
div class="container"
  - flash.each do |key,value|
    = content_tag(:div, value, class: "alert alert-info #{key}")

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | LinkRack
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    header
      = render 'layouts/header'

    div class="container"
      /div class="row"
      = yield

    footer class="container"
      = render 'layouts/footer'

app/views/links/_form.html.slim
= form_for @link, html:{class: "form-horizontal"} do |f|
  - if @link.errors.any?
    #error_explanation
      h2 = "#{pluralize(@link.errors.count, "error")} prohibited this link from being saved:"
      ul
        - @link.errors.full_messages.each do |message|
          li = message
  div class="form-group"
    .field
      = f.label :sort, class: "col-sm-2 control-label"
      div class="col-sm-2"
        = f.number_field :sort, class: "form-control"
  div class="form-group"
    .field
      = f.label :description, class: "col-sm-2 control-label"
      div class="col-sm-10"
        = f.text_field :description, class: "form-control"
  div class="form-group"
    .field
      = f.label :link, class: "col-sm-2 control-label"
      div class="col-sm-10"
        = f.text_area :link, class: "form-control"
  div class="form-group"
    .field
      = f.label :enabled, class: "col-sm-2 control-label"
      div class="col-sm-1"
        = f.check_box :enabled, class: "form-control", checked: true
  div class="form-group"
    .actions = f.submit class: "col-sm-offset-2 col-sm-2 btn btn-primary"

app/views/links/edit.html.slim
h1 Editing link

== render 'form'

=> link_to 'Show', @link, class: "btn btn-default"
/'|
=< link_to 'Back', links_path, class: "btn btn-default"

app/views/links/index.html.slim
h1 Listing links

table class="table table-hover"
  thead
    tr
      th Sort
      th Description
      th Preview
      /th Link
      th Enabled
      th
      th
      th

  tbody
    - @links.each do |link|
      tr
        td = link.sort
        td = link.description
        td == link.link
        /td = link.link
        td = link.enabled
        td = link_to 'Show', link, class: "btn btn-default btn-block"
        td = link_to 'Edit', edit_link_path(link), class: "btn btn-primary btn-block"
        td = link_to 'Destroy', link, data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-danger btn-block"

br

= link_to 'New Link', new_link_path, class: "btn btn-success"

app/views/links/new.html.slim
h1 New link

== render 'form'

= link_to 'Back', links_path, class: "btn btn-default"

app/views/links/show.html.slim
h1 Links#show
p Find me in app/views/links/show.html.slim

p#notice = notice

table class="table"
  tbody
    tr
      td class="col-sm-2"
        strong Sort
      td
        = @link.sort
    tr
      td class="col-sm-2"
        strong Description
      td
        = @link.description
    tr
      td class="col-sm-2"
        strong Link
      td
        = @link.link
    tr
      td class="col-sm-2"
        strong Enabled
      td
        = @link.enabled

=> link_to 'Edit', edit_link_path(@link), class: "btn btn-primary"
/'|
=< link_to 'Back', links_path, class: "btn btn-default"

app/views/static_pages/about.html.slim
h1
  | About
p
  | Find me in app/views/static_pages/about.html.erb

app/views/static_pages/help.html.slim
h1
  | Help
p
  | Find me in app/views/static_pages/help.html.erb

app/views/static_pages/home.html.slim
h1
  | Home
p
  | Find me in app/views/static_pages/home.html.erb
h2
  | WARNING!! Work in Progress.
h2
  | Please don't use. （´ ・(ェ)・` ）

app/views/users/index.html.slim
h1 Users#index
p Find me in app/views/users/index.html.slim

table class="table"
  thead
    tr
      /th ID
      th Email
      th Key
      /th Name

  tbody
    - @users.each do |user|
      tr
        /td = user.id
        td = user.email
        td = user.hashed_email
        /td = user.name
        td = link_to 'Detail', user, class: "btn btn-default btn-block"

app/views/users/show.html.slim
h1 Users#show
p Find me in app/views/users/show.html.slim

p#notice = notice

table class="table"
  tbody
    tr
      td class="col-sm-2"
        strong ID
      td
        = @user.id
    tr
      td class="col-sm-2"
        strong Email
      td
        = @user.email
    tr
      td class="col-sm-2"
        strong Name
      td
        = @user.name
    tr
      td class="col-sm-2"
        strong MalsKey
      td
        = @user.hashed_email

=> link_to 'Signout', destroy_user_session_path, class: "btn btn-primary", method: :delete if user_signed_in?
/'|
=> link_to 'Unsubscribe', '/users', class: "btn btn-danger", method: :delete, data: { confirm: "Really want to UNSUBSCRIBE?\nYour links will be removed!!" }  if user_signed_in?
/'|
=< link_to 'Back', users_path, class: "btn btn-default"